# Generated by Django 4.1.5 on 2023-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
