# Generated by Django 4.1.5 on 2023-01-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
