# Generated by Django 4.1.5 on 2023-01-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.DateField(max_length=250),
        ),
    ]
