# Generated by Django 4.1.5 on 2023-01-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blog_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="url",
        ),
    ]
